%make the vector state for passing it over to the ODE solver. The derived
%fields of the structure must be consistent to the public fields. This
%means that, if points/springs have been added/removed, or their
%dynamical_X flag has been changed, or spring ends have been changed, or
%modifications have 
function evolvedState = makeEvolvedState(ss)
  %make the vector state
  vars = {ss.pos, ss.vel, ss.m, ss.k, ss.r, ss.c};
  d = ss.dynamic;
  logs = [d.pos d.vel d.m d.k d.r d.c];
  aux = [ss.dynVars(logs); vars(logs)]; %.30
  evolvedState = struct(aux{:});
%   evolvedState = [reshape(ss.pos(ss.dynamical_p,:), [],1); ...
%                   reshape(ss.vel(ss.dynamical_p,:),[],1);  ...
%                   ss.m(ss.dynamical_m); ...
%                   ss.k(ss.dynamical_k); ...
%                   ss.r(ss.dynamical_r); ...
%                   ss.c(ss.dynamical_c); ...
%                   ...%ss.u(ss.dynamical_u)  ...
%                   ];
end

