%constructor
function rec = EnergyRecorder(ss, space, inc)
  rec = struct(...
    'TYPE',             {'EnergyRecorder'}, ...
    'callback',         {[]}, ...
    'inc',              {[]}, ... 
    'e',                {[]}, ... 
    'ts',               {[]}, ... 
    'index',            {[]}, ... 
    'straightforward',  {[]}  ... 
    );
  rec.inc = inc;
  rec.e = zeros(space,1);
  rec.ts = zeros(space,1);
  rec.index = 1;
  rec.straightforward = false;
end
