%constructor
function rec = MemRecorder(ss, dynspace, notdynspace, incdyn, incnotdyn)
rec = struct(...
  'TYPE',         {'MemRecorder'}, ...
  'callback',     {[]}, ...
  'emptyState',   {[]}, ...
  'fieldSets',    {[]}, ...
  'dyn',          {[]}, ...
  'dynTs',        {[]}, ...
  'notdyn',       {[]}, ...
  'notdynTs',     {[]}, ...
  'incdyn',       {[]}, ...
  'incnotdyn',    {[]}, ...
  'dynIndex',     {[]}, ...
  'notdynIndex',  {[]} ...
  );
rec.fieldSets = getBasicSystemFieldSets(ss, true);
rec.incdyn = incdyn;
rec.incnotdyn = incnotdyn;
rec.dyn = cell(dynspace,1);
rec.dynTs = zeros(dynspace,1);
rec.notdyn = cell(notdynspace,1);
rec.notdynTs = zeros(notdynspace,1);
rec.dynIndex = 1;
rec.notdynIndex = 1;



