function data = cameraProps(ax, data)

props = {
'CameraPositionMode', ...
'CameraPosition', ...
'CameraTargetMode', ...
'CameraTarget', ...
'CameraUpVectorMode', ...
'CameraUpVector', ...
'CameraViewAngleMode', ...
'CameraViewAngle', ...
'Projection', ...
};

if isempty(ax)
  ax = gca;
end

if nargin<2
  data = get(ax, props);
else
  cellfun(@(a,b)set(ax, a, b), props, data);
end